name: game_repository
description: A Very Good Project created by Very Good CLI.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  web_socket_client: ^0.1.0
  player_repository:
    path: ../../api/packages/player_repository
  api:
    path: ../../api
  models:
    path: ../../api/packages/models

dev_dependencies:
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^5.0.0
