name: chat_repository
description: A new Flutter package project.
version: 0.0.1
publish_to: none

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  api:
    path: ../../api
  models:
    path: ../../api/packages/models
  player_repository:
    path: ../../api/packages/player_repository
  web_socket_client: ^0.1.0

dev_dependencies:
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^5.0.0