name: api
description: An new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  broadcast_bloc: ^0.1.0-dev.2
  dart_frog: ^1.0.0
  dart_frog_web_socket: ^1.0.0
  equatable: ^2.0.5
  json_annotation: ^4.8.0
  logging: ^1.2.0
  models:
    path: packages/models
  player_repository:
    path: packages/player_repository
  shelf_cors_headers: ^0.1.5
  uuid: ^3.0.7

dev_dependencies:
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^5.0.0
