name: Web App
on:
  push:
    branches: [ develop ]
jobs:
  build:
    name: Build Web
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
      - uses: bluefireteam/flutter-gh-pages@v7
        with:
          webRenderer: canvaskit
          customArgs: --target lib/main_development.dart
